services:
  vpn4friends:
    build: .
    container_name: vpn4friends
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    network_mode: "host"

  vpn4friends_api:
    build: .
    container_name: vpn4friends-api
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./miniapp/dist:/app/miniapp/dist:ro
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8001

  nginx:
    image: nginx:alpine
    container_name: vpn4friends-nginx
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./miniapp/dist:/usr/share/nginx/miniapp:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  api_proxy:
    image: cloudflare/cloudflared:latest
    container_name: vpn4friends-api-tunnel
    restart: unless-stopped
    command: tunnel --loglevel debug --protocol http2 run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    network_mode: "host"
