"""Add ConnectionPreset model and extend VpnProfile

Revision ID: 08940f47ba4f
Revises: 
Create Date: 2026-01-12 13:00:18.389303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08940f47ba4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # Users table and index
    if not inspector.has_table("users"):
        op.create_table(
            "users",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("telegram_id", sa.BigInteger(), nullable=False),
            sa.Column("username", sa.String(length=255), nullable=True),
            sa.Column("full_name", sa.String(length=255), nullable=False),
            sa.Column("is_admin", sa.Boolean(), nullable=False),
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            ),
            sa.PrimaryKeyConstraint("id"),
        )

    existing_indexes = {idx["name"] for idx in inspector.get_indexes("users")}
    index_name = op.f("ix_users_telegram_id")
    if index_name not in existing_indexes:
        op.create_index(index_name, "users", ["telegram_id"], unique=True)

    # VPN profiles
    if not inspector.has_table("vpn_profiles"):
        op.create_table(
            "vpn_profiles",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column("protocol_name", sa.String(length=50), nullable=False),
            sa.Column("profile_data", sa.JSON(), nullable=False),
            sa.Column("is_active", sa.Boolean(), nullable=False),
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            ),
            sa.Column("label", sa.String(length=100), nullable=True),
            sa.Column("settings", sa.JSON(), nullable=True),
            sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
            sa.PrimaryKeyConstraint("id"),
        )

    # VPN requests
    if not inspector.has_table("vpn_requests"):
        op.create_table(
            "vpn_requests",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column(
                "status",
                sa.Enum("PENDING", "APPROVED", "REJECTED", name="requeststatus"),
                nullable=False,
            ),
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            ),
            sa.Column("processed_at", sa.DateTime(), nullable=True),
            sa.Column("admin_comment", sa.String(length=500), nullable=True),
            sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
            sa.PrimaryKeyConstraint("id"),
        )

    # Connection presets
    if not inspector.has_table("connection_presets"):
        op.create_table(
            "connection_presets",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column("profile_id", sa.Integer(), nullable=False),
            sa.Column("name", sa.String(length=100), nullable=False),
            sa.Column("app_type", sa.String(length=50), nullable=False),
            sa.Column("format", sa.String(length=50), nullable=False),
            sa.Column("options", sa.JSON(), nullable=True),
            sa.ForeignKeyConstraint(["profile_id"], ["vpn_profiles.id"]),
            sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
            sa.PrimaryKeyConstraint("id"),
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connection_presets')
    op.drop_table('vpn_requests')
    op.drop_table('vpn_profiles')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
