"""Add otp_code to WebAccessRequest

Revision ID: 2c92690c1613
Revises: d11997d46868
Create Date: 2026-03-30 14:58:33.746648

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c92690c1613"
down_revision: str | Sequence[str] | None = "d11997d46868"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("web_access_requests", sa.Column("otp_code", sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("web_access_requests", "otp_code")
    # ### end Alembic commands ###
